package com.lpirro.core.extensions

fun String.countryCodeToEmoji(): String {
    return emoji[this] ?: ""
}

val emoji: Map<String, String> = mapOf(
    "IND" to "🇮🇳",
    "NGA" to "🇳🇬",
    "KEN" to "🇰🇪",
    "ITA" to "🇮🇹",
    "USA" to "🇺🇸",
    "CUB" to "🇨🇺",
    "GBR" to "🇬🇧",
    "ZAF" to "🇿🇦",
    "POL" to "🇵🇱",
    "GHA" to "🇬🇭",
    "MAR" to "🇲🇦",
    "IDN" to "🇮🇩",
    "ESP" to "🇪🇸",
    "BRA" to "🇧🇷",
    "DEU" to "🇩🇪",
    "FRA" to "🇫🇷",
    "ARE" to "🇦🇷",
    "CMR" to "🇨🇲",
    "MEX" to "🇲🇪",
    "UZB" to "🇺🇿",
    "IRN" to "🇮🇷",
    "SAU" to "🇸🇦",
    "TUR" to "🇹🇷",
    "CHL" to "🇨🇱",
    "TZA" to "🇹🇿",
    "UKR" to "🇺🇦",
    "NPL" to "🇳🇵",
    "PAK" to "🇵🇰",
    "PER" to "🇵🇪",
    "UGA" to "🇺🇬",
    "COL" to "🇨🇴",
    "AUS" to "🇦🇺",
    "AUT" to "🇦🇹",
    "ARG" to "🇦🇷",
    "ETH" to "🇪🇹",
    "CHN" to "🇨🇳",
    "RUS" to "🇷🇺",
    "PHL" to "🇵🇭",
    "VEN" to "🇻🇪",
    "MYS" to "🇲🇾",
    "GRC" to "🇬🇷",
    "CAN" to "🇨🇦",
    "BGD" to "🇧🇩",
    "ZWE" to "🇿🇼",
    "JPN" to "🇯🇵",
    "THA" to "🇹🇭",
    "LKA" to "🇱🇰",
    "ROU" to "🇷🇴",
    "ISR" to "🇮🇱",
    "VNM" to "🇻🇳",
    "NLD" to "🇳🇱",
    "EGY" to "🇪🇬",
    "ECU" to "🇪🇨",
    "SGP" to "🇸🇬",
    "DOM" to "🇩🇴",
    "GEO" to "🇬🇪",
    "DZA" to "🇩🇿",
    "KAZ" to "🇰🇿",
    "KOR" to "🇰🇷",
    "BEL" to "🇧🇪",
    "LBN" to "🇱🇧",
    "CZE" to "🇨🇿",
    "QAT" to "🇶🇦",
    "TJK" to "🇹🇯",
    "MDV" to "🇲🇻",
    "IRQ" to "🇮🇶",
    "HKG" to "🇭🇰",
    "SWE" to "🇸🇪",
    "TWN" to "🇹🇼",
    "AZE" to "🇦🇿",
    "TUN" to "🇹🇳",
    "ARM" to "🇦🇲",
    "KHM" to "🇰🇭",
    "KWT" to "🇰🇼",
    "NOR" to "🇳🇴",
    "HRV" to "🇭🇷",
    "MDA" to "🇲🇩",
    "FIN" to "🇫🇮",
    "CHE" to "🇨🇭",
    "ALB" to "🇦🇱",
)
